package swu

import (
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"sync"
	"time"
)

// WiresharkDebugger writes IKEv2 and ESP decryption table entries.
type WiresharkDebugger struct {
	mu       sync.Mutex
	file     *os.File
	enabled  bool
	filePath string
	writeErr error
}

// NewWiresharkDebugger restores the original enabled/path constructor.
func NewWiresharkDebugger(enabled bool, filePath string) (*WiresharkDebugger, error) {
	if !enabled || filePath == "" {
		return &WiresharkDebugger{}, nil
	}
	debugger := &WiresharkDebugger{enabled: true, filePath: filePath}
	file, err := os.OpenFile(filePath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o600)
	if err != nil {
		return nil, fmt.Errorf("打开调试文件失败: %w", err)
	}
	debugger.file = file
	debugger.writeLine("# IKEv2/ESP Decryption Table")
	debugger.writeLine("# Generated by swu-go at " + time.Now().Format(time.RFC3339))
	debugger.writeLine("# Format: wireshark ikev2_decryption_table")
	debugger.writeLine("")
	if debugger.writeErr != nil {
		return nil, errors.Join(debugger.writeErr, file.Close())
	}
	return debugger, nil
}

// NewDetachedWiresharkDebugger retains the additive empty-debugger capability
// that predated restoration of the original constructor signature.
func NewDetachedWiresharkDebugger() *WiresharkDebugger {
	return &WiresharkDebugger{}
}

// SetOutput retains the additive output attachment API.
func (w *WiresharkDebugger) SetOutput(path string) error {
	if w == nil {
		return errors.New("swu: nil Wireshark debugger")
	}
	if path == "" {
		return nil
	}
	file, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o600)
	if err != nil {
		return err
	}
	w.mu.Lock()
	previous := w.file
	w.file, w.enabled, w.filePath = file, true, path
	w.mu.Unlock()
	if previous != nil {
		return previous.Close()
	}
	return nil
}

// LogIKESAKeys writes one IKEv2 decryption-table row.
func (w *WiresharkDebugger) LogIKESAKeys(
	spiI, spiR uint64,
	skEi, skEr, skAi, skAr []byte,
	encryptionID, integrityID uint16,
) {
	w.writeLine(fmt.Sprintf(
		"\"IKEv2\" \"%016x\" \"%016x\" \"%s\" \"%s\" \"%s\" \"%s\" \"%d\" \"%d\"",
		spiI, spiR, hex.EncodeToString(skEi), hex.EncodeToString(skEr),
		hex.EncodeToString(skAi), hex.EncodeToString(skAr), encryptionID, integrityID,
	))
}

// LogESPKeys writes one ESP security-association row.
func (w *WiresharkDebugger) LogESPKeys(
	spi uint32,
	sourceIP, destinationIP string,
	key []byte,
	encryptionID uint16,
) {
	w.writeLine(fmt.Sprintf(
		"\"ESP\" \"0x%08x\" \"%s\" \"%s\" \"%s\" \"%d\"",
		spi, sourceIP, destinationIP, hex.EncodeToString(key), encryptionID,
	))
}

// LogChildSA writes both directions of a CHILD_SA.
func (w *WiresharkDebugger) LogChildSA(
	spiIn, spiOut uint32,
	localIP, remoteIP string,
	keyIn, keyOut []byte,
	encryptionID uint16,
) {
	w.writeLine("# Child SA established at " + time.Now().Format(time.RFC3339))
	w.LogESPKeys(spiIn, remoteIP, localIP, keyIn, encryptionID)
	w.LogESPKeys(spiOut, localIP, remoteIP, keyOut, encryptionID)
	w.writeLine("")
}

// LogRaw writes a diagnostic comment using the original formatting contract.
func (w *WiresharkDebugger) LogRaw(format string, arguments ...interface{}) {
	w.writeLine("# " + fmt.Sprintf(format, arguments...))
}

func (w *WiresharkDebugger) writeLine(line string) {
	if w == nil {
		return
	}
	w.mu.Lock()
	defer w.mu.Unlock()
	if !w.enabled || w.file == nil || w.writeErr != nil {
		return
	}
	_, w.writeErr = w.file.WriteString(line + "\n")
}

// Close closes the key log and returns any deferred write failure.
func (w *WiresharkDebugger) Close() error {
	if w == nil {
		return nil
	}
	w.mu.Lock()
	defer w.mu.Unlock()
	var closeErr error
	if w.file != nil {
		closeErr = w.file.Close()
		w.file = nil
	}
	w.enabled = false
	return errors.Join(w.writeErr, closeErr)
}
